package com.foodpurby.ondbstorage;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "APP_SETTINGS".
 */
public class AppSettings {

    private Long id;
    private String cityKey;
    private String cityName;
    private String areaKey;
    private String areaName;
    private String gcmTokenKey;
    private Boolean vibrateOnCartChange;

    public AppSettings() {
    }

    public AppSettings(Long id) {
        this.id = id;
    }

    public AppSettings(Long id, String cityKey, String cityName, String areaKey, String areaName, String gcmTokenKey, Boolean vibrateOnCartChange) {
        this.id = id;
        this.cityKey = cityKey;
        this.cityName = cityName;
        this.areaKey = areaKey;
        this.areaName = areaName;
        this.gcmTokenKey = gcmTokenKey;
        this.vibrateOnCartChange = vibrateOnCartChange;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCityKey() {
        return cityKey;
    }

    public void setCityKey(String cityKey) {
        this.cityKey = cityKey;
    }

    public String getCityName() {
        return cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    public String getAreaKey() {
        return areaKey;
    }

    public void setAreaKey(String areaKey) {
        this.areaKey = areaKey;
    }

    public String getAreaName() {
        return areaName;
    }

    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    public String getGcmTokenKey() {
        return gcmTokenKey;
    }

    public void setGcmTokenKey(String gcmTokenKey) {
        this.gcmTokenKey = gcmTokenKey;
    }

    public Boolean getVibrateOnCartChange() {
        return vibrateOnCartChange;
    }

    public void setVibrateOnCartChange(Boolean vibrateOnCartChange) {
        this.vibrateOnCartChange = vibrateOnCartChange;
    }

}
