package com.foodpurby.ondbstorage;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CART_PRODUCTS_INGREDIENTS".
 */
public class CartProductsIngredients {

    private Long id;
    /** Not-null value. */
    private String cartProductKey;
    /** Not-null value. */
    private String ingredientsKey;
    /** Not-null value. */
    private String restaurantBranchKey;
    /** Not-null value. */
    private String productKey;
    /** Not-null value. */
    private String ingredientsTypeKey;
    /** Not-null value. */
    private String ingredientsName;
    private Double price;
    private String sortingNumber;
    private Boolean activeStatus;

    public CartProductsIngredients() {
    }

    public CartProductsIngredients(Long id) {
        this.id = id;
    }

    public CartProductsIngredients(Long id, String cartProductKey, String ingredientsKey, String restaurantBranchKey, String productKey, String ingredientsTypeKey, String ingredientsName, Double price, String sortingNumber, Boolean activeStatus) {
        this.id = id;
        this.cartProductKey = cartProductKey;
        this.ingredientsKey = ingredientsKey;
        this.restaurantBranchKey = restaurantBranchKey;
        this.productKey = productKey;
        this.ingredientsTypeKey = ingredientsTypeKey;
        this.ingredientsName = ingredientsName;
        this.price = price;
        this.sortingNumber = sortingNumber;
        this.activeStatus = activeStatus;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCartProductKey() {
        return cartProductKey;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCartProductKey(String cartProductKey) {
        this.cartProductKey = cartProductKey;
    }

    /** Not-null value. */
    public String getIngredientsKey() {
        return ingredientsKey;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIngredientsKey(String ingredientsKey) {
        this.ingredientsKey = ingredientsKey;
    }

    /** Not-null value. */
    public String getRestaurantBranchKey() {
        return restaurantBranchKey;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRestaurantBranchKey(String restaurantBranchKey) {
        this.restaurantBranchKey = restaurantBranchKey;
    }

    /** Not-null value. */
    public String getProductKey() {
        return productKey;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setProductKey(String productKey) {
        this.productKey = productKey;
    }

    /** Not-null value. */
    public String getIngredientsTypeKey() {
        return ingredientsTypeKey;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIngredientsTypeKey(String ingredientsTypeKey) {
        this.ingredientsTypeKey = ingredientsTypeKey;
    }

    /** Not-null value. */
    public String getIngredientsName() {
        return ingredientsName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIngredientsName(String ingredientsName) {
        this.ingredientsName = ingredientsName;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public String getSortingNumber() {
        return sortingNumber;
    }

    public void setSortingNumber(String sortingNumber) {
        this.sortingNumber = sortingNumber;
    }

    public Boolean getActiveStatus() {
        return activeStatus;
    }

    public void setActiveStatus(Boolean activeStatus) {
        this.activeStatus = activeStatus;
    }

}
