package com.foodpurby.ondbstorage;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CART_PRODUCTS_INGREDIENTS".
*/
public class CartProductsIngredientsDao extends AbstractDao<CartProductsIngredients, Long> {

    public static final String TABLENAME = "CART_PRODUCTS_INGREDIENTS";

    /**
     * Properties of entity CartProductsIngredients.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CartProductKey = new Property(1, String.class, "cartProductKey", false, "CART_PRODUCT_KEY");
        public final static Property IngredientsKey = new Property(2, String.class, "ingredientsKey", false, "INGREDIENTS_KEY");
        public final static Property RestaurantBranchKey = new Property(3, String.class, "restaurantBranchKey", false, "RESTAURANT_BRANCH_KEY");
        public final static Property ProductKey = new Property(4, String.class, "productKey", false, "PRODUCT_KEY");
        public final static Property IngredientsTypeKey = new Property(5, String.class, "ingredientsTypeKey", false, "INGREDIENTS_TYPE_KEY");
        public final static Property IngredientsName = new Property(6, String.class, "ingredientsName", false, "INGREDIENTS_NAME");
        public final static Property Price = new Property(7, Double.class, "price", false, "PRICE");
        public final static Property SortingNumber = new Property(8, String.class, "sortingNumber", false, "SORTING_NUMBER");
        public final static Property ActiveStatus = new Property(9, Boolean.class, "activeStatus", false, "ACTIVE_STATUS");
    };


    public CartProductsIngredientsDao(DaoConfig config) {
        super(config);
    }
    
    public CartProductsIngredientsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CART_PRODUCTS_INGREDIENTS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"CART_PRODUCT_KEY\" TEXT NOT NULL ," + // 1: cartProductKey
                "\"INGREDIENTS_KEY\" TEXT NOT NULL ," + // 2: ingredientsKey
                "\"RESTAURANT_BRANCH_KEY\" TEXT NOT NULL ," + // 3: restaurantBranchKey
                "\"PRODUCT_KEY\" TEXT NOT NULL ," + // 4: productKey
                "\"INGREDIENTS_TYPE_KEY\" TEXT NOT NULL ," + // 5: ingredientsTypeKey
                "\"INGREDIENTS_NAME\" TEXT NOT NULL ," + // 6: ingredientsName
                "\"PRICE\" REAL," + // 7: price
                "\"SORTING_NUMBER\" TEXT," + // 8: sortingNumber
                "\"ACTIVE_STATUS\" INTEGER);"); // 9: activeStatus
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CART_PRODUCTS_INGREDIENTS\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, CartProductsIngredients entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getCartProductKey());
        stmt.bindString(3, entity.getIngredientsKey());
        stmt.bindString(4, entity.getRestaurantBranchKey());
        stmt.bindString(5, entity.getProductKey());
        stmt.bindString(6, entity.getIngredientsTypeKey());
        stmt.bindString(7, entity.getIngredientsName());
 
        Double price = entity.getPrice();
        if (price != null) {
            stmt.bindDouble(8, price);
        }
 
        String sortingNumber = entity.getSortingNumber();
        if (sortingNumber != null) {
            stmt.bindString(9, sortingNumber);
        }
 
        Boolean activeStatus = entity.getActiveStatus();
        if (activeStatus != null) {
            stmt.bindLong(10, activeStatus ? 1L: 0L);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public CartProductsIngredients readEntity(Cursor cursor, int offset) {
        CartProductsIngredients entity = new CartProductsIngredients( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // cartProductKey
            cursor.getString(offset + 2), // ingredientsKey
            cursor.getString(offset + 3), // restaurantBranchKey
            cursor.getString(offset + 4), // productKey
            cursor.getString(offset + 5), // ingredientsTypeKey
            cursor.getString(offset + 6), // ingredientsName
            cursor.isNull(offset + 7) ? null : cursor.getDouble(offset + 7), // price
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // sortingNumber
            cursor.isNull(offset + 9) ? null : cursor.getShort(offset + 9) != 0 // activeStatus
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, CartProductsIngredients entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCartProductKey(cursor.getString(offset + 1));
        entity.setIngredientsKey(cursor.getString(offset + 2));
        entity.setRestaurantBranchKey(cursor.getString(offset + 3));
        entity.setProductKey(cursor.getString(offset + 4));
        entity.setIngredientsTypeKey(cursor.getString(offset + 5));
        entity.setIngredientsName(cursor.getString(offset + 6));
        entity.setPrice(cursor.isNull(offset + 7) ? null : cursor.getDouble(offset + 7));
        entity.setSortingNumber(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setActiveStatus(cursor.isNull(offset + 9) ? null : cursor.getShort(offset + 9) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(CartProductsIngredients entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(CartProductsIngredients entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
