package com.foodpurby.ondbstorage;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CATEGORY".
*/
public class CategoryDao extends AbstractDao<Category, Long> {

    public static final String TABLENAME = "CATEGORY";

    /**
     * Properties of entity Category.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property RestaurantKey = new Property(1, String.class, "restaurantKey", false, "RESTAURANT_KEY");
        public final static Property RestaurantBranchKey = new Property(2, String.class, "restaurantBranchKey", false, "RESTAURANT_BRANCH_KEY");
        public final static Property CategoryKey = new Property(3, String.class, "categoryKey", false, "CATEGORY_KEY");
        public final static Property CategoryName = new Property(4, String.class, "categoryName", false, "CATEGORY_NAME");
        public final static Property ParentCategoryKey = new Property(5, String.class, "parentCategoryKey", false, "PARENT_CATEGORY_KEY");
        public final static Property SortingNumber = new Property(6, Integer.class, "sortingNumber", false, "SORTING_NUMBER");
        public final static Property ActiveStatus = new Property(7, Boolean.class, "activeStatus", false, "ACTIVE_STATUS");
    };


    public CategoryDao(DaoConfig config) {
        super(config);
    }
    
    public CategoryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CATEGORY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"RESTAURANT_KEY\" TEXT NOT NULL ," + // 1: restaurantKey
                "\"RESTAURANT_BRANCH_KEY\" TEXT NOT NULL ," + // 2: restaurantBranchKey
                "\"CATEGORY_KEY\" TEXT NOT NULL ," + // 3: categoryKey
                "\"CATEGORY_NAME\" TEXT," + // 4: categoryName
                "\"PARENT_CATEGORY_KEY\" TEXT NOT NULL ," + // 5: parentCategoryKey
                "\"SORTING_NUMBER\" INTEGER," + // 6: sortingNumber
                "\"ACTIVE_STATUS\" INTEGER);"); // 7: activeStatus
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CATEGORY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Category entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getRestaurantKey());
        stmt.bindString(3, entity.getRestaurantBranchKey());
        stmt.bindString(4, entity.getCategoryKey());
 
        String categoryName = entity.getCategoryName();
        if (categoryName != null) {
            stmt.bindString(5, categoryName);
        }
        stmt.bindString(6, entity.getParentCategoryKey());
 
        Integer sortingNumber = entity.getSortingNumber();
        if (sortingNumber != null) {
            stmt.bindLong(7, sortingNumber);
        }
 
        Boolean activeStatus = entity.getActiveStatus();
        if (activeStatus != null) {
            stmt.bindLong(8, activeStatus ? 1L: 0L);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Category readEntity(Cursor cursor, int offset) {
        Category entity = new Category( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // restaurantKey
            cursor.getString(offset + 2), // restaurantBranchKey
            cursor.getString(offset + 3), // categoryKey
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // categoryName
            cursor.getString(offset + 5), // parentCategoryKey
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // sortingNumber
            cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0 // activeStatus
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Category entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRestaurantKey(cursor.getString(offset + 1));
        entity.setRestaurantBranchKey(cursor.getString(offset + 2));
        entity.setCategoryKey(cursor.getString(offset + 3));
        entity.setCategoryName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setParentCategoryKey(cursor.getString(offset + 5));
        entity.setSortingNumber(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setActiveStatus(cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Category entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Category entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
