package com.foodpurby.ondbstorage;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CATEGORY".
 */
public class Category {

    private Long id;
    /** Not-null value. */
    private String restaurantKey;
    /** Not-null value. */
    private String restaurantBranchKey;
    /** Not-null value. */
    private String categoryKey;
    private String categoryName;
    /** Not-null value. */
    private String parentCategoryKey;
    private Integer sortingNumber;
    private Boolean activeStatus;

    public Category() {
    }

    public Category(Long id) {
        this.id = id;
    }

    public Category(Long id, String restaurantKey, String restaurantBranchKey, String categoryKey, String categoryName, String parentCategoryKey, Integer sortingNumber, Boolean activeStatus) {
        this.id = id;
        this.restaurantKey = restaurantKey;
        this.restaurantBranchKey = restaurantBranchKey;
        this.categoryKey = categoryKey;
        this.categoryName = categoryName;
        this.parentCategoryKey = parentCategoryKey;
        this.sortingNumber = sortingNumber;
        this.activeStatus = activeStatus;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getRestaurantKey() {
        return restaurantKey;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRestaurantKey(String restaurantKey) {
        this.restaurantKey = restaurantKey;
    }

    /** Not-null value. */
    public String getRestaurantBranchKey() {
        return restaurantBranchKey;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRestaurantBranchKey(String restaurantBranchKey) {
        this.restaurantBranchKey = restaurantBranchKey;
    }

    /** Not-null value. */
    public String getCategoryKey() {
        return categoryKey;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCategoryKey(String categoryKey) {
        this.categoryKey = categoryKey;
    }

    public String getCategoryName() {
        return categoryName;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    /** Not-null value. */
    public String getParentCategoryKey() {
        return parentCategoryKey;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setParentCategoryKey(String parentCategoryKey) {
        this.parentCategoryKey = parentCategoryKey;
    }

    public Integer getSortingNumber() {
        return sortingNumber;
    }

    public void setSortingNumber(Integer sortingNumber) {
        this.sortingNumber = sortingNumber;
    }

    public Boolean getActiveStatus() {
        return activeStatus;
    }

    public void setActiveStatus(Boolean activeStatus) {
        this.activeStatus = activeStatus;
    }

}
