package com.foodpurby.ondbstorage;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CUISINE".
*/
public class CuisineDao extends AbstractDao<Cuisine, Long> {

    public static final String TABLENAME = "CUISINE";

    /**
     * Properties of entity Cuisine.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property RestaurantKey = new Property(1, String.class, "restaurantKey", false, "RESTAURANT_KEY");
        public final static Property RestaurantBranchKey = new Property(2, String.class, "restaurantBranchKey", false, "RESTAURANT_BRANCH_KEY");
        public final static Property GroupKey = new Property(3, String.class, "groupKey", false, "GROUP_KEY");
        public final static Property CuisineKey = new Property(4, String.class, "cuisineKey", false, "CUISINE_KEY");
        public final static Property CuisineName = new Property(5, String.class, "cuisineName", false, "CUISINE_NAME");
        public final static Property SortingNumber = new Property(6, String.class, "sortingNumber", false, "SORTING_NUMBER");
        public final static Property ActiveStatus = new Property(7, Boolean.class, "activeStatus", false, "ACTIVE_STATUS");
    };


    public CuisineDao(DaoConfig config) {
        super(config);
    }
    
    public CuisineDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CUISINE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"RESTAURANT_KEY\" TEXT NOT NULL ," + // 1: restaurantKey
                "\"RESTAURANT_BRANCH_KEY\" TEXT NOT NULL ," + // 2: restaurantBranchKey
                "\"GROUP_KEY\" TEXT NOT NULL ," + // 3: groupKey
                "\"CUISINE_KEY\" TEXT NOT NULL ," + // 4: cuisineKey
                "\"CUISINE_NAME\" TEXT," + // 5: cuisineName
                "\"SORTING_NUMBER\" TEXT," + // 6: sortingNumber
                "\"ACTIVE_STATUS\" INTEGER);"); // 7: activeStatus
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CUISINE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Cuisine entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getRestaurantKey());
        stmt.bindString(3, entity.getRestaurantBranchKey());
        stmt.bindString(4, entity.getGroupKey());
        stmt.bindString(5, entity.getCuisineKey());
 
        String cuisineName = entity.getCuisineName();
        if (cuisineName != null) {
            stmt.bindString(6, cuisineName);
        }
 
        String sortingNumber = entity.getSortingNumber();
        if (sortingNumber != null) {
            stmt.bindString(7, sortingNumber);
        }
 
        Boolean activeStatus = entity.getActiveStatus();
        if (activeStatus != null) {
            stmt.bindLong(8, activeStatus ? 1L: 0L);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Cuisine readEntity(Cursor cursor, int offset) {
        Cuisine entity = new Cuisine( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // restaurantKey
            cursor.getString(offset + 2), // restaurantBranchKey
            cursor.getString(offset + 3), // groupKey
            cursor.getString(offset + 4), // cuisineKey
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // cuisineName
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // sortingNumber
            cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0 // activeStatus
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Cuisine entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRestaurantKey(cursor.getString(offset + 1));
        entity.setRestaurantBranchKey(cursor.getString(offset + 2));
        entity.setGroupKey(cursor.getString(offset + 3));
        entity.setCuisineKey(cursor.getString(offset + 4));
        entity.setCuisineName(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setSortingNumber(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setActiveStatus(cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Cuisine entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Cuisine entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
