package com.foodpurby.ondbstorage;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CUISINE_FILTER".
 */
public class CuisineFilter {

    private Long id;
    /** Not-null value. */
    private String cuisineKey;
    private String cuisineName;
    private String sortingNumber;
    private Boolean activeStatus;

    public CuisineFilter() {
    }

    public CuisineFilter(Long id) {
        this.id = id;
    }

    public CuisineFilter(Long id, String cuisineKey, String cuisineName, String sortingNumber, Boolean activeStatus) {
        this.id = id;
        this.cuisineKey = cuisineKey;
        this.cuisineName = cuisineName;
        this.sortingNumber = sortingNumber;
        this.activeStatus = activeStatus;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCuisineKey() {
        return cuisineKey;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCuisineKey(String cuisineKey) {
        this.cuisineKey = cuisineKey;
    }

    public String getCuisineName() {
        return cuisineName;
    }

    public void setCuisineName(String cuisineName) {
        this.cuisineName = cuisineName;
    }

    public String getSortingNumber() {
        return sortingNumber;
    }

    public void setSortingNumber(String sortingNumber) {
        this.sortingNumber = sortingNumber;
    }

    public Boolean getActiveStatus() {
        return activeStatus;
    }

    public void setActiveStatus(Boolean activeStatus) {
        this.activeStatus = activeStatus;
    }

}
