package com.foodpurby.ondbstorage;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cuisineFilterDaoConfig;
    private final DaoConfig restaurantBranchDaoConfig;
    private final DaoConfig groupDaoConfig;
    private final DaoConfig cuisineDaoConfig;
    private final DaoConfig categoryDaoConfig;
    private final DaoConfig productsDaoConfig;
    private final DaoConfig ingredientsCategoryDaoConfig;
    private final DaoConfig ingredientsDaoConfig;
    private final DaoConfig cartProductsDaoConfig;
    private final DaoConfig cartProductsIngredientsDaoConfig;
    private final DaoConfig userAddressDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig appSettingsDaoConfig;

    private final CuisineFilterDao cuisineFilterDao;
    private final RestaurantBranchDao restaurantBranchDao;
    private final GroupDao groupDao;
    private final CuisineDao cuisineDao;
    private final CategoryDao categoryDao;
    private final ProductsDao productsDao;
    private final IngredientsCategoryDao ingredientsCategoryDao;
    private final IngredientsDao ingredientsDao;
    private final CartProductsDao cartProductsDao;
    private final CartProductsIngredientsDao cartProductsIngredientsDao;
    private final UserAddressDao userAddressDao;
    private final UserDao userDao;
    private final AppSettingsDao appSettingsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cuisineFilterDaoConfig = daoConfigMap.get(CuisineFilterDao.class).clone();
        cuisineFilterDaoConfig.initIdentityScope(type);

        restaurantBranchDaoConfig = daoConfigMap.get(RestaurantBranchDao.class).clone();
        restaurantBranchDaoConfig.initIdentityScope(type);

        groupDaoConfig = daoConfigMap.get(GroupDao.class).clone();
        groupDaoConfig.initIdentityScope(type);

        cuisineDaoConfig = daoConfigMap.get(CuisineDao.class).clone();
        cuisineDaoConfig.initIdentityScope(type);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        productsDaoConfig = daoConfigMap.get(ProductsDao.class).clone();
        productsDaoConfig.initIdentityScope(type);

        ingredientsCategoryDaoConfig = daoConfigMap.get(IngredientsCategoryDao.class).clone();
        ingredientsCategoryDaoConfig.initIdentityScope(type);

        ingredientsDaoConfig = daoConfigMap.get(IngredientsDao.class).clone();
        ingredientsDaoConfig.initIdentityScope(type);

        cartProductsDaoConfig = daoConfigMap.get(CartProductsDao.class).clone();
        cartProductsDaoConfig.initIdentityScope(type);

        cartProductsIngredientsDaoConfig = daoConfigMap.get(CartProductsIngredientsDao.class).clone();
        cartProductsIngredientsDaoConfig.initIdentityScope(type);

        userAddressDaoConfig = daoConfigMap.get(UserAddressDao.class).clone();
        userAddressDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        appSettingsDaoConfig = daoConfigMap.get(AppSettingsDao.class).clone();
        appSettingsDaoConfig.initIdentityScope(type);

        cuisineFilterDao = new CuisineFilterDao(cuisineFilterDaoConfig, this);
        restaurantBranchDao = new RestaurantBranchDao(restaurantBranchDaoConfig, this);
        groupDao = new GroupDao(groupDaoConfig, this);
        cuisineDao = new CuisineDao(cuisineDaoConfig, this);
        categoryDao = new CategoryDao(categoryDaoConfig, this);
        productsDao = new ProductsDao(productsDaoConfig, this);
        ingredientsCategoryDao = new IngredientsCategoryDao(ingredientsCategoryDaoConfig, this);
        ingredientsDao = new IngredientsDao(ingredientsDaoConfig, this);
        cartProductsDao = new CartProductsDao(cartProductsDaoConfig, this);
        cartProductsIngredientsDao = new CartProductsIngredientsDao(cartProductsIngredientsDaoConfig, this);
        userAddressDao = new UserAddressDao(userAddressDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        appSettingsDao = new AppSettingsDao(appSettingsDaoConfig, this);

        registerDao(CuisineFilter.class, cuisineFilterDao);
        registerDao(RestaurantBranch.class, restaurantBranchDao);
        registerDao(Group.class, groupDao);
        registerDao(Cuisine.class, cuisineDao);
        registerDao(Category.class, categoryDao);
        registerDao(Products.class, productsDao);
        registerDao(IngredientsCategory.class, ingredientsCategoryDao);
        registerDao(Ingredients.class, ingredientsDao);
        registerDao(CartProducts.class, cartProductsDao);
        registerDao(CartProductsIngredients.class, cartProductsIngredientsDao);
        registerDao(UserAddress.class, userAddressDao);
        registerDao(User.class, userDao);
        registerDao(AppSettings.class, appSettingsDao);
    }
    
    public void clear() {
        cuisineFilterDaoConfig.getIdentityScope().clear();
        restaurantBranchDaoConfig.getIdentityScope().clear();
        groupDaoConfig.getIdentityScope().clear();
        cuisineDaoConfig.getIdentityScope().clear();
        categoryDaoConfig.getIdentityScope().clear();
        productsDaoConfig.getIdentityScope().clear();
        ingredientsCategoryDaoConfig.getIdentityScope().clear();
        ingredientsDaoConfig.getIdentityScope().clear();
        cartProductsDaoConfig.getIdentityScope().clear();
        cartProductsIngredientsDaoConfig.getIdentityScope().clear();
        userAddressDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
        appSettingsDaoConfig.getIdentityScope().clear();
    }

    public CuisineFilterDao getCuisineFilterDao() {
        return cuisineFilterDao;
    }

    public RestaurantBranchDao getRestaurantBranchDao() {
        return restaurantBranchDao;
    }

    public GroupDao getGroupDao() {
        return groupDao;
    }

    public CuisineDao getCuisineDao() {
        return cuisineDao;
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public ProductsDao getProductsDao() {
        return productsDao;
    }

    public IngredientsCategoryDao getIngredientsCategoryDao() {
        return ingredientsCategoryDao;
    }

    public IngredientsDao getIngredientsDao() {
        return ingredientsDao;
    }

    public CartProductsDao getCartProductsDao() {
        return cartProductsDao;
    }

    public CartProductsIngredientsDao getCartProductsIngredientsDao() {
        return cartProductsIngredientsDao;
    }

    public UserAddressDao getUserAddressDao() {
        return userAddressDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public AppSettingsDao getAppSettingsDao() {
        return appSettingsDao;
    }

}
