package com.foodpurby.ondbstorage;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "INGREDIENTS_CATEGORY".
 */
public class IngredientsCategory {

    private Long id;
    /** Not-null value. */
    private String ingredientsCategoryKey;
    private String restaurantBranchKey;
    private String productKey;
    private String ingredientsCategoryName;
    private Integer minSelection;
    private Integer maxSelection;
    private Integer requiredSelection;
    private Boolean mandatoryStatus;
    private Boolean multiSelectStatus;
    private Double price;
    private Integer sortingNumber;
    private Boolean activeStatus;

    public IngredientsCategory() {
    }

    public IngredientsCategory(Long id) {
        this.id = id;
    }

    public IngredientsCategory(Long id, String ingredientsCategoryKey, String restaurantBranchKey, String productKey, String ingredientsCategoryName, Integer minSelection, Integer maxSelection, Integer requiredSelection, Boolean mandatoryStatus, Boolean multiSelectStatus, Double price, Integer sortingNumber, Boolean activeStatus) {
        this.id = id;
        this.ingredientsCategoryKey = ingredientsCategoryKey;
        this.restaurantBranchKey = restaurantBranchKey;
        this.productKey = productKey;
        this.ingredientsCategoryName = ingredientsCategoryName;
        this.minSelection = minSelection;
        this.maxSelection = maxSelection;
        this.requiredSelection = requiredSelection;
        this.mandatoryStatus = mandatoryStatus;
        this.multiSelectStatus = multiSelectStatus;
        this.price = price;
        this.sortingNumber = sortingNumber;
        this.activeStatus = activeStatus;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getIngredientsCategoryKey() {
        return ingredientsCategoryKey;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIngredientsCategoryKey(String ingredientsCategoryKey) {
        this.ingredientsCategoryKey = ingredientsCategoryKey;
    }

    public String getRestaurantBranchKey() {
        return restaurantBranchKey;
    }

    public void setRestaurantBranchKey(String restaurantBranchKey) {
        this.restaurantBranchKey = restaurantBranchKey;
    }

    public String getProductKey() {
        return productKey;
    }

    public void setProductKey(String productKey) {
        this.productKey = productKey;
    }

    public String getIngredientsCategoryName() {
        return ingredientsCategoryName;
    }

    public void setIngredientsCategoryName(String ingredientsCategoryName) {
        this.ingredientsCategoryName = ingredientsCategoryName;
    }

    public Integer getMinSelection() {
        return minSelection;
    }

    public void setMinSelection(Integer minSelection) {
        this.minSelection = minSelection;
    }

    public Integer getMaxSelection() {
        return maxSelection;
    }

    public void setMaxSelection(Integer maxSelection) {
        this.maxSelection = maxSelection;
    }

    public Integer getRequiredSelection() {
        return requiredSelection;
    }

    public void setRequiredSelection(Integer requiredSelection) {
        this.requiredSelection = requiredSelection;
    }

    public Boolean getMandatoryStatus() {
        return mandatoryStatus;
    }

    public void setMandatoryStatus(Boolean mandatoryStatus) {
        this.mandatoryStatus = mandatoryStatus;
    }

    public Boolean getMultiSelectStatus() {
        return multiSelectStatus;
    }

    public void setMultiSelectStatus(Boolean multiSelectStatus) {
        this.multiSelectStatus = multiSelectStatus;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public Integer getSortingNumber() {
        return sortingNumber;
    }

    public void setSortingNumber(Integer sortingNumber) {
        this.sortingNumber = sortingNumber;
    }

    public Boolean getActiveStatus() {
        return activeStatus;
    }

    public void setActiveStatus(Boolean activeStatus) {
        this.activeStatus = activeStatus;
    }

}
