package com.foodpurby.ondbstorage;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER_ADDRESS".
 */
public class UserAddress {

    private Long id;
    /** Not-null value. */
    private String userAddressKey;
    private Boolean defaultStatus;
    private String companyName;
    private String flatNo;
    private String locationName;
    private String postalCode;
    private String landmark;
    private String deliveryInstrutions;
    private String cityKey;
    private String cityName;
    private String areaKey;
    private String areaName;
    private String annotation;
    private Boolean deliveryValid;
    private Boolean deleteStatus;
    private Boolean activeStatus;

    public UserAddress() {
    }

    public UserAddress(Long id) {
        this.id = id;
    }

    public UserAddress(Long id, String userAddressKey, Boolean defaultStatus, String companyName, String flatNo, String locationName, String postalCode, String landmark, String deliveryInstrutions, String cityKey, String cityName, String areaKey, String areaName, String annotation, Boolean deliveryValid, Boolean deleteStatus, Boolean activeStatus) {
        this.id = id;
        this.userAddressKey = userAddressKey;
        this.defaultStatus = defaultStatus;
        this.companyName = companyName;
        this.flatNo = flatNo;
        this.locationName = locationName;
        this.postalCode = postalCode;
        this.landmark = landmark;
        this.deliveryInstrutions = deliveryInstrutions;
        this.cityKey = cityKey;
        this.cityName = cityName;
        this.areaKey = areaKey;
        this.areaName = areaName;
        this.annotation = annotation;
        this.deliveryValid = deliveryValid;
        this.deleteStatus = deleteStatus;
        this.activeStatus = activeStatus;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUserAddressKey() {
        return userAddressKey;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserAddressKey(String userAddressKey) {
        this.userAddressKey = userAddressKey;
    }

    public Boolean getDefaultStatus() {
        return defaultStatus;
    }

    public void setDefaultStatus(Boolean defaultStatus) {
        this.defaultStatus = defaultStatus;
    }

    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public String getFlatNo() {
        return flatNo;
    }

    public void setFlatNo(String flatNo) {
        this.flatNo = flatNo;
    }

    public String getLocationName() {
        return locationName;
    }

    public void setLocationName(String locationName) {
        this.locationName = locationName;
    }

    public String getPostalCode() {
        return postalCode;
    }

    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    public String getLandmark() {
        return landmark;
    }

    public void setLandmark(String landmark) {
        this.landmark = landmark;
    }

    public String getDeliveryInstrutions() {
        return deliveryInstrutions;
    }

    public void setDeliveryInstrutions(String deliveryInstrutions) {
        this.deliveryInstrutions = deliveryInstrutions;
    }

    public String getCityKey() {
        return cityKey;
    }

    public void setCityKey(String cityKey) {
        this.cityKey = cityKey;
    }

    public String getCityName() {
        return cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    public String getAreaKey() {
        return areaKey;
    }

    public void setAreaKey(String areaKey) {
        this.areaKey = areaKey;
    }

    public String getAreaName() {
        return areaName;
    }

    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    public String getAnnotation() {
        return annotation;
    }

    public void setAnnotation(String annotation) {
        this.annotation = annotation;
    }

    public Boolean getDeliveryValid() {
        return deliveryValid;
    }

    public void setDeliveryValid(Boolean deliveryValid) {
        this.deliveryValid = deliveryValid;
    }

    public Boolean getDeleteStatus() {
        return deleteStatus;
    }

    public void setDeleteStatus(Boolean deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    public Boolean getActiveStatus() {
        return activeStatus;
    }

    public void setActiveStatus(Boolean activeStatus) {
        this.activeStatus = activeStatus;
    }

}
