package com.foodpurby.ondbstorage;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER".
 */
public class User {

    private Long id;
    /** Not-null value. */
    private String userKey;
    /** Not-null value. */
    private String userEMail;
    /** Not-null value. */
    private String userFirstName;
    /** Not-null value. */
    private String userLastName;
    /** Not-null value. */
    private String userMobile;
    /** Not-null value. */
    private String userToken;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String userKey, String userEMail, String userFirstName, String userLastName, String userMobile, String userToken) {
        this.id = id;
        this.userKey = userKey;
        this.userEMail = userEMail;
        this.userFirstName = userFirstName;
        this.userLastName = userLastName;
        this.userMobile = userMobile;
        this.userToken = userToken;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUserKey() {
        return userKey;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserKey(String userKey) {
        this.userKey = userKey;
    }

    /** Not-null value. */
    public String getUserEMail() {
        return userEMail;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserEMail(String userEMail) {
        this.userEMail = userEMail;
    }

    /** Not-null value. */
    public String getUserFirstName() {
        return userFirstName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserFirstName(String userFirstName) {
        this.userFirstName = userFirstName;
    }

    /** Not-null value. */
    public String getUserLastName() {
        return userLastName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserLastName(String userLastName) {
        this.userLastName = userLastName;
    }

    /** Not-null value. */
    public String getUserMobile() {
        return userMobile;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserMobile(String userMobile) {
        this.userMobile = userMobile;
    }

    /** Not-null value. */
    public String getUserToken() {
        return userToken;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserToken(String userToken) {
        this.userToken = userToken;
    }

}
